database:
  image: mariadb
  environment:
    - "MYSQL_ROOT_PASSWORD=root"
    - "MYSQL_DATABASE=testjee"

queuer:
  image: webcenter/activemq
  ports:
    - "8161:8161"

server:
  build: ./server
  ports:
    - "9080:8080"

listener:
  build: ./listener
  ports:
    - "10080:8080"
  links:
    - queuer
    - database
    - server