
package test.jee.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceBeanService", targetNamespace = "http://server.jee.test/", wsdlLocation = "http://server:8080/webservices/WebServiceBean?wsdl")
public class WebServiceBeanService
    extends Service
{

    private final static URL WEBSERVICEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEBEANSERVICE_EXCEPTION;
    private final static QName WEBSERVICEBEANSERVICE_QNAME = new QName("http://server.jee.test/", "WebServiceBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://server:8080/webservices/WebServiceBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEBEANSERVICE_WSDL_LOCATION = url;
        WEBSERVICEBEANSERVICE_EXCEPTION = e;
    }

    public WebServiceBeanService() {
        super(__getWsdlLocation(), WEBSERVICEBEANSERVICE_QNAME);
    }

    public WebServiceBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEBEANSERVICE_QNAME, features);
    }

    public WebServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEBEANSERVICE_QNAME);
    }

    public WebServiceBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEBEANSERVICE_QNAME, features);
    }

    public WebServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceBean
     */
    @WebEndpoint(name = "WebServiceBeanPort")
    public WebServiceBean getWebServiceBeanPort() {
        return super.getPort(new QName("http://server.jee.test/", "WebServiceBeanPort"), WebServiceBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceBean
     */
    @WebEndpoint(name = "WebServiceBeanPort")
    public WebServiceBean getWebServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.jee.test/", "WebServiceBeanPort"), WebServiceBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEBEANSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEBEANSERVICE_EXCEPTION;
        }
        return WEBSERVICEBEANSERVICE_WSDL_LOCATION;
    }

}
