
package test.jee.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceBean", targetNamespace = "http://server.jee.test/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceBean {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "service", targetNamespace = "http://server.jee.test/", className = "test.jee.server.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://server.jee.test/", className = "test.jee.server.ServiceResponse")
    public String service(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
